name: Mount Guava ranking

on:
 workflow_call:
 workflow_dispatch: 

jobs:
  genOSM:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Partner merchants markdown
        id: genOSMData
        run: bash genOSMData.sh ${{ vars.OSM_FILTER }} 
      - name: Upload to git
        id: uploadGit
        shell: bash
        run: |
          curl -s https://raw.githubusercontent.com/juancolchete/utils/main/gitUpload.sh | bash /dev/stdin ${{ vars.GIT_UPLOAD_PARAMS }} "bot: ${{ github.workflow }}"
